# version: '3'
services:
  web:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306  # name (db) must be the same as below (db:)
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - frontend
      - backend
    depends_on:
      - db
    restart: always
    ports:
      - "8000:80"
  db:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - backend
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306"
volumes:
  dbdata:
networks:
  frontend:
  backend: